### ISSUE TITLE
mosquitto-go-auth crash (and mosquitto crashes followed suit) for unexpected hash format

### ISSUE THREAD

**Issue by wildstray** [iegomez/mosquitto-go-auth#50]
After a test witeeh incomplete password hashes in db, mosquitto service crashed with SIGABRT.
In the logs:
```
gen 31 12:55:39 jdev6 mosquitto[27775]: panic: runtime error: index out of range
gen 31 12:55:39 jdev6 mosquitto[27775]: goroutine 17 [running, locked to thread]:
gen 31 12:55:39 jdev6 mosquitto[27775]: github.com/iegomez/mosquitto-go-auth/common.HashCompare(0x55a41daccea0, 0x5, 0xc000124500, 0x38, 0x46)
gen 31 12:55:39 jdev6 mosquitto[27775]:         /home/andrea/mosquitto-go-auth-0.6.1/common/utils.go:134 +0x17c
gen 31 12:55:39 jdev6 mosquitto[27775]: github.com/iegomez/mosquitto-go-auth/backends.Postgres.GetUser(0xc00012d560, 0x55a41dac3e90, 0x9, 0x55a41dac3f80, 0x4, 0x55a41dac4010, 0x7, 0x55a41dac40b0, 0x7, 0x55a41dac4160, ...)
gen 31 12:55:39 jdev6 mosquitto[27775]:         /home/andrea/mosquitto-go-auth-0.6.1/backends/postgres.go:164 +0x1c5
gen 31 12:55:39 jdev6 mosquitto[27775]: main.CheckBackendsAuth(0x55a41dacc720, 0x5, 0x55a41daccea0, 0x5, 0x7f1369251c20)
gen 31 12:55:39 jdev6 mosquitto[27775]:         /home/andrea/mosquitto-go-auth-0.6.1/go-auth.go:672 +0x20c
gen 31 12:55:39 jdev6 mosquitto[27775]: main.AuthUnpwdCheck(0x55a41dacc720, 0x5, 0x55a41daccea0, 0x5, 0x38)
gen 31 12:55:39 jdev6 mosquitto[27775]:         /home/andrea/mosquitto-go-auth-0.6.1/go-auth.go:494 +0x462
gen 31 12:55:39 jdev6 mosquitto[27775]: main._cgoexpwrap_ebd210e0adf1_AuthUnpwdCheck(0x55a41dacc720, 0x5, 0x55a41daccea0, 0x5, 0x2525252525252525)
gen 31 12:55:39 jdev6 mosquitto[27775]:         _cgo_gotypes.go:59 +0x4b
gen 31 12:55:39 jdev6 systemd[1]: mosquitto.service: Main process exited, code=killed, status=6/ABRT
gen 31 12:55:39 jdev6 systemd[1]: mosquitto.service: Failed with result 'signal'.
```

So I realized that passwordHash in HashCompare() is not validated. This issue can simply solved checking the len of resulting slice after the Split:

```
func HashCompare(password string, passwordHash string) bool {
        hashSplit := strings.Split(passwordHash, "$")
	if len(hashSplit) < 5 {
		return false
	}
```

**Comment by coldfire84** [comment]
I think the fix for this has been introduced in this PR: https://github.com/iegomez/mosquitto-go-auth/pull/45

**Comment by iegomez** [comment]
Yeah, Chris was looking into that on his PR so I didn't make any separate efforts, but I'd be happy to accept this change as a separate specific PR.

**Comment by iegomez** [comment]
I just did some refactoring and took the time to include this. Thanks for the report @wildstray!
